
admin = Admin.create!(
  firstname: 'global',
  lastname: 'admin',
  email: 'global.admin@email.com',
  username: 'global.admin',
  password: 'password',
  password_confirmation: 'password',
  enabled: true,
  otp_required: false,
  otp_enabled: true
)


tenant = Tenant.create!(
  company_name: 'First Test Manpower Services Inc.',
  principal: 'first test owner',
  company_address: 'company address',
  company_email: 'firsttestmanpowerservices@agency.com',
  license: '123456789',
  contact_number: '987654321',
  subdomain: "testmanpower",
  subscription: 'enterprise',
)

owner = Owner.create!(
  firstname: 'test',
  lastname: 'owner',
  username: 'test.owner',
  email: 'test.owner@email.com',
  password: 'password',
  password_confirmation: 'password',
  enabled: true,
  otp_required: true,
  otp_enabled: true,
  tenant_id: tenant && tenant.id
)

100.times do |n| 
    Employee.create!(
    firstname: 'test',
    lastname: "employee#{n}",
    username: "test.employee#{n}",
    email: "test.employee#{n}@email.com",
    password: 'password',
    password_confirmation: 'password',
    enabled: true,
    otp_required: true,
    otp_enabled: true,
    tenant_id: tenant && tenant.id
  )
end

applicant = Applicant.create!(
  firstname: 'test1',
  lastname: 'applicant',
  username: 'test1.applicant',
  email: 'test1.applicant@email.com',
  password: 'password',
  password_confirmation: 'password',
  enabled: true,
  otp_required: true,
  otp_enabled: true,
)

applicant = Applicant.create!(
  firstname: 'test2',
  lastname: 'applicant',
  username: 'test2.applicant',
  email: 'test2.applicant@email.com',
  password: 'password',
  password_confirmation: 'password',
  enabled: true,
  otp_required: true,
  otp_enabled: true,
)

profession = [
  "Dentist",
  "Registered Nurse",
  "Pharmacist",
  "Computer Systems Analyst",
  "Physician",
  "Database Administrator",
  "Software Developer",
  "Physical Therapist",
  "Web Developer",
  "Dental Hygienist",
  "Occupational Therapist",
  "Veterinarian",
  "Computer Programmer",
  "School Psychologist",
  "Physical Therapist Assistant",
  "Interpreter & Translator",
  "Mechanical Engineer",
  "Veterinary Technologist & Technician",
  "Epidemiologist",
  "IT Manager",
  "Graphic Designer",
  "Financial Analyst",
  "Civil Engineer",
  "Electrical Engineer",
  "Data Scientist",
  "Marketing Manager",
  "Pharmacy Technician",
  "Dental Assistant",
  "Radiologic Technologist",
  "Psychologist",
  "Medical Technologist",
  "Accountant",
  "Environmental Scientist",
  "Nurse Practitioner",
  "Physiotherapist",
  "Architect",
  "Social Worker",
  "Human Resources Manager",
  "Chef",
  "Pilot",
  "Geologist",
  "Interior Designer",
  "Mechanic",
  "Electrician",
  "Firefighter",
  "Police Officer",
  "Paramedic",
  "Plumber",
  "Real Estate Agent",
  "Writer",
  "Artist",
  "Photographer",
  "Fashion Designer",
  "Teacher",
  "Librarian",
  "Biomedical Engineer",
  "Chemical Engineer",
  "Astronomer",
  "Zoologist",
  "Athletic Trainer",
  "Nutritionist",
  "Meteorologist",
  "Film Director",
  "Actor",
  "Musician",
  "Veterinary Surgeon",
  "Phlebotomist",
  "Speech Therapist",
  "Orthodontist",
  "Orthopedic Surgeon",
  "Forensic Scientist",
  "Marine Biologist",
  "Aerospace Engineer",
  "Civil Rights Attorney",
  "Judge",
  "Foreign Service Officer",
  "Environmental Lawyer",
  "Museum Curator",
  "Screenwriter",
  "News Anchor",
  "Public Relations Specialist",
  "Sociologist",
  "Cartoonist",
  "Botanist",
  "Oceanographer",
  "Product Manager",
  "Project Manager",
  "Air Traffic Controller",
  "Commercial Pilot",
  "Astronaut",
  "Political Analyst",
  "Radio Host",
  "Video Game Developer",
  "Ethical Hacker",
  "Blockchain Developer",
  "Social Media Manager",
  "Content Creator",
  "Clinical Psychologist",
  "Forensic Psychologist",
  "Nuclear Engineer",
  "Chemist",
  "Genetic Counselor",
  "Market Research Analyst",
  "Logistician",
  "Economist",
  "Investment Banker",
  "Actuary",
  "Park Ranger",
  "Speech Pathologist",
  "Financial Planner",
  "Urban Planner",
  "Robotics Engineer",
  "Environmental Engineer",
  "Technical Writer",
  "Biostatistician",
  "Criminal Investigator",
  "Sports Agent",
  "Video Editor",
  "Archaeologist",
  "Film Producer",
  "Agricultural Engineer",
  "Industrial Designer",
  "Criminal Defense Attorney",
  "Sculptor",
  "Animator",
  "Dietitian",
  "Surveyor",
  "Meteorologist",
  "Cinematographer",
  "Bioinformatician",
  "Neurologist",
  "Radiologist",
  "Forensic Pathologist",
  "Urban Designer",
  "Film Critic",
  "Sound Engineer",
  "Tour Guide",
  "Cybersecurity Analyst",
  "Environmental Planner",
  "Renewable Energy Engineer",
  "Technical Illustrator",
  "Cryptocurrency Analyst",
  "Database Manager",
  "Urban Planner",
  "Renewable Energy Technician",
  "Chemical Technician",
  "Space Scientist",
  "Blockchain Analyst",
  "Industrial Engineer",
  "Audiologist",
  "Renewable Energy Consultant",
  "Sustainability Consultant",
  "Biochemist",
  "Financial Analyst",
  "Media Planner",
  "Music Producer",
  "Sports Coach",
  "Cartographer",
  "Geographic Information Systems Analyst",
  "Environmental Consultant",
  "Robotics Technician",
  "Automotive Engineer",
  "Environmental Compliance Specialist",
  "Geoscientist",
  "Geotechnical Engineer",
  "Bioinformatics Scientist",
  "Materials Engineer",
  "Food Scientist",
  "Political Scientist",
  "Financial Controller",
  "Data Analyst",
  "Operations Manager",
  "Brand Manager",
  "Market Analyst",
  "Sound Designer",
  "UX Designer",
  "Web Designer",
  "Ergonomist",
  "Solar Energy Technician",
  "Wind Energy Technician",
  "Radiation Therapist",
  "Game Developer",
  "Aerospace Technician",
  "Telecommunications Engineer",
  "Civil Rights Activist",
  "Human Rights Lawyer",
  "Historian",
  "Archivist",
  "Graphic Artist",
  "Interpreter",
  "Translator",
  "Environmental Biologist",
  "Ecologist",
  "Marine Biologist",
  "Hydrologist",
  "Mathematician",
  "Statistician",
  "Biomedical Scientist",
  "Podiatrist",
  "Chiropractor",
  "Occupational Therapist",
  "Speech and Language Therapist",
  "Radiation Oncologist",
  "Clinical Laboratory Scientist",
  "Pharmaceutical Sales Representative",
  "Technical Support Specialist",
  "Network Administrator",
  "Systems Analyst",
  "Database Administrator",
  "Software Tester",
  "Quality Assurance Analyst",
  "Graphic Designer",
  "User Interface Designer",
  "Front-End Developer",
  "Back-End Developer",
  "Full-Stack Developer",
  "DevOps Engineer",
  "Cloud Solutions Architect",
  "Cybersecurity Engineer",
  "Machine Learning Engineer",
  "Artificial Intelligence Engineer",
  "Quantum Computing Scientist",
  "Neurosurgeon",
  "Cardiologist",
  "Dermatologist",
  "Gastroenterologist",
  "Pediatrician",
  "Obstetrician",
  "Gynecologist",
  "Orthopedic Surgeon",
  "Ophthalmologist",
  "Urologist",
  "Anesthesiologist",
  "Pathologist",
  "Radiologist",
  "Forensic Pathologist",
  "Prosthodontist",
  "Endodontist",
  "Periodontist",
  "Oral and Maxillofacial Surgeon",
  "Orthodontist",
  "Emergency Medicine Physician",
  "Sports Medicine Physician",
  "Geriatrician",
  "Hematologist",
  "Nephrologist",
  "Pulmonologist",
  "Rheumatologist",
  "Allergist",
  "Immunologist",
  "Neurologist",
  "Oncologist",
  "Psychiatrist",
  "Family Physician",
  "General Surgeon",
  "Internal Medicine Physician",
  "Infectious Disease Specialist",
  "Medical Geneticist",
  "Nuclear Medicine Physician",
  "Pain Management Physician",
  "Sleep Medicine Physician",
  "Hospitalist",
  "Palliative Care Physician",
  "Dermatopathologist",
  "Cytopathologist",
  "Neuropathologist",
  "Forensic Pathologist",
  "Pathologist Assistant",
  "Clinical Laboratory Scientist",
  "Medical Technologist",
  "Phlebotomist",
  "Cytogenetic Technologist",
  "Histotechnologist",
  "Cytotechnologist",
  "Medical Laboratory Technician",
  "Medical Laboratory Assistant",
  "Clinical Research Coordinator",
  "Clinical Research Associate",
  "Clinical Trial Manager",
  "Clinical Data Manager",
  "Biostatistician",
  "Epidemiologist",
  "Infection Control Specialist",
  "Public Health Educator",
  "Healthcare Administrator",
  "Health Information Manager",
  "Healthcare Consultant",
  "Healthcare Quality Analyst",
  "Medical Writer",
  "Medical Illustrator",
  "Medical Animator",
  "Pharmaceutical Scientist",
  "Pharmaceutical Researcher",
  "Clinical Research Scientist",
  "Clinical Pharmacologist",
  "Pharmaceutical Manufacturing Technician",
  "Pharmacy Assistant",
  "Pharmacy Technician",
  "Radiologic Technologist",
  "Radiation Therapist",
  "MRI Technologist",
  "Nuclear Medicine Technologist",
  "Cardiovascular Technologist",
  "Medical Dosimetrist",
  "Sonographer",
  "Medical Laboratory Scientist",
  "Surgical Technologist",
  "Dental Laboratory Technician",
  "Dental Assistant",
  "Orthodontic Assistant",
  "Dental Hygienist",
  "Dental Therapist",
  "Oral and Maxillofacial Surgeon Assistant",
  "Endodontic Assistant",
  "Periodontal Assistant",
  "Prosthodontic Assistant",
  "Dental Ceramist",
  "Dental Laboratory Manager",
  "Dental Laboratory Owner",
  "Dental Equipment Sales Representative",
  "Orthodontic Technician",
  "Prosthodontic Technician",
  "Dental Laboratory Sales Representative",
  "Dental Hygiene Educator",
  "Dental Materials Scientist",
  "Dental Industry Analyst",
  "Dental Public Health Researcher",
  "Dental Clinical Researcher",
  "Dental Technology Educator",
  "Forensic Odontologist",
  "Pediatric Dentist",
  "Periodontist",
  "Oral Pathologist",
  "Oral and Maxillofacial Radiologist",
  "Oral Medicine Specialist",
  "Dental Anesthesiologist",
  "Pediatric Dentistry Researcher",
  "Orthodontist",
  "Prosthodontist",
  "Public Health Dentist",
  "Academic Dentist",
  "Private Practice Dentist",
  "Hospital Dentist",
  "Community Health Dentist",
  "Oral Surgeon",
  "Dental Epidemiologist",
  "Dental Consultant",
  "Registered Nurse",
  "Nurse Practitioner",
  "Clinical Nurse Specialist",
  "Nurse Anesthetist",
  "Nurse Midwife",
  "Public Health Nurse",
  "School Nurse",
  "Pediatric Nurse",
  "Obstetric Nurse",
  "Gynecology Nurse",
  "Critical Care Nurse",
  "Emergency Nurse",
  "Trauma Nurse",
  "Surgical Nurse",
  "Operating Room Nurse",
  "Perioperative Nurse",
  "Orthopedic Nurse",
]

location = [
'Doha, Qatar',
'California, USA',
'Sydney, Australia',
'London, United Kingdom',
'New York, USA',
'Tokyo, Japan',
'Paris, France',
'Berlin, Germany',
'Toronto, Canada',
'Singapore, Singapore',
'Dubai, UAE',
'Beijing, China',
'Rio de Janeiro, Brazil',
'Mumbai, India',
'Cape Town, South Africa',
'Moscow, Russia',
'Stockholm, Sweden',
'Mexico City, Mexico',
'Buenos Aires, Argentina',
'Auckland, New Zealand'
]

description = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquam nisi sit amet sagittis pretium. Sed molestie erat vitae dolor pharetra lobortis. Nunc scelerisque eget odio vel laoreet. Quisque ac congue arcu. Morbi faucibus pellentesque vehicula. Donec hendrerit ullamcorper eros at commodo. Nam non tincidunt nisi, et laoreet urna. Phasellus nec ligula dolor. Praesent convallis ornare neque, in facilisis ex dignissim id. Quisque blandit venenatis mollis. Donec eget tortor bibendum purus aliquet sodales scelerisque ut nulla. Fusce vulputate tincidunt molestie.

Integer sollicitudin congue dolor, eu porttitor mauris aliquet ut. Maecenas sodales aliquam molestie. Etiam in lorem quam. Duis pretium id ante quis euismod. Phasellus et odio vel urna venenatis mattis. Morbi posuere bibendum nisi, sit amet eleifend orci aliquet nec. Morbi fermentum elit id consequat mollis. Ut vel condimentum nibh. Quisque ut elit tortor. Sed ac urna at augue elementum ornare. Praesent sodales est non hendrerit viverra.

Vestibulum dignissim lectus sed luctus volutpat. Proin non mollis quam. Ut pulvinar risus odio, ac fringilla libero egestas eget. Phasellus sodales sollicitudin arcu, vel semper justo convallis a. Suspendisse potenti. In at condimentum erat. Duis pellentesque convallis nibh, at maximus tellus consequat vitae. Donec in mollis magna, vel mollis enim. Nunc mollis nisl varius, blandit est nec, convallis nisi. Phasellus sed varius tellus. Suspendisse potenti. Pellentesque vel aliquet ex. Aliquam tristique lacinia nibh, non placerat diam sollicitudin tincidunt. Praesent fringilla condimentum nunc, vitae auctor velit rutrum a. In malesuada scelerisque massa, vel euismod arcu luctus at. Nulla commodo vestibulum gravida.

Praesent ullamcorper sodales malesuada. Cras eu consequat felis. Quisque luctus porta purus sit amet hendrerit. Nulla a metus malesuada, lacinia ipsum sed, tincidunt turpis. Ut metus nisi, sollicitudin id egestas non, interdum et dui. Morbi in elit turpis. Vivamus sed aliquet justo. Donec volutpat lorem a ligula lacinia, sit amet pellentesque lorem lobortis. Cras erat dolor, malesuada lobortis cursus ut, interdum non enim. Donec mollis, purus in semper accumsan, ligula ipsum ullamcorper ligula, eget consectetur quam augue id quam. Cras id nisi rhoncus lacus porta pellentesque at vitae urna. Suspendisse ullamcorper vestibulum sapien, venenatis egestas purus ornare id. Donec congue, nisl ac efficitur posuere, lectus dolor consequat enim, nec rutrum tortor diam rutrum est. Cras posuere posuere laoreet.

Donec vel justo erat. Phasellus in odio nec lacus varius sollicitudin sit amet id mi. Nulla nec aliquet eros. Vestibulum eu pellentesque augue, at euismod turpis. Cras condimentum malesuada diam vitae bibendum. Duis sodales imperdiet sem, in bibendum magna. In eu ornare nulla, ac ornare massa. Nullam tempor faucibus interdum. Aliquam erat volutpat. Suspendisse sed auctor augue. Cras blandit augue ut ipsum auctor porttitor. Aenean pulvinar eu quam vitae consequat. Nam blandit nulla vitae purus imperdiet, in euismod nibh ornare. Aenean hendrerit quis nibh vel posuere. Phasellus et ipsum luctus, placerat ex quis, hendrerit lacus. Curabitur magna justo, maximus ac dapibus sit amet, pharetra sit amet orci."]
requirement = ["Bachelor's degree, excellent communication skills, problem-solving abilities, team player, attention to detail, time management skills, basic computer skills and valid driver's license"]
title = ['HR Manager', 'Chief Executive Officer', 'Talent Acquisition']
job_type = ['Full-Time', 'Temporary', 'Part-Time']

# Create 50 employers (50x20 = 1000 total jobs)
50.times do |employer_index|
  employer = Employer.create!(
    company_name: "Test Company #{employer_index + 1}",
    company_address: "Company Address #{employer_index + 1}",
    company_email: "company#{employer_index + 1}@example.com",
    company_phone: "12345678#{employer_index + 1}",
    company_poc_name: "John Doe#{employer_index + 1}",
    company_poc_title: title.sample,
    tenant_id: tenant.id
  )

  # Create 20 jobs for each employer
  20.times do |job_index|
    job = Job.create!(
      job_name: profession.sample,
      job_description: description.sample,
      job_requirement: requirement.sample,
      job_headcount: rand(5..20),
      job_salary: rand(3000..8000),
      job_currency: 'USD',
      job_location: location.sample,
      job_type: job_type.sample,
      tags: "Tag #{job_index + 1}",
      deadline: (Date.today + rand(1..90).days),
      employer_id: employer.id
    )
  end
end
